---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create custom repo file
      copy:
        dest: "{{ custom_yum_repofile_filepath }}"
        content: |
          [Confluent.custom]
          async = 1
          baseurl = "{{confluent_common_repository_redhat_main_baseurl}}"
          enabled = 1
          gpgcheck = 1
          gpgkey = "{{confluent_common_repository_redhat_main_gpgkey}}"
          name = Custom Confluent repository
          [Confluent.clients.custom]
          async = 1
          baseurl = "{{confluent_common_repository_redhat_clients_baseurl}}"
          enabled = 1
          gpgcheck = 1
          gpgkey = "{{confluent_common_repository_redhat_clients_gpgkey}}"
          name = Custom Confluent repository (clients)
    - name: Download Jolokia Jar
      get_url:
        url: http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar
        dest: "{{ jolokia_jar_url }}"
    - name: Download Jmx Exporter Jar
      get_url:
        url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar
        dest: "{{ jmxexporter_jar_url }}"
