---
- name: Copy the client configuration file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
  when: kerberos_configure|bool

- name: Copy the client configuration file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5/krb5.conf
  when: kerberos_configure|bool

- name: Convert kerberos files to z/OS encoding
  when: ansible_os_family == "OS/390"
  include_role:
    name: common
    tasks_from: zos_convert_files.yml
  vars:
    paths_to_convert:
      - /etc/krb5.conf
      - /etc/krb5/krb5.conf

- name: Create Keytabs Directory
  file:
    path: "{{ kerberos_keytab_destination_path | dirname }}"
    state: directory
    group: "{{kerberos_group}}"
    mode: 0750

- name: Copy in Keytab File
  copy:
    src: "{{kerberos_keytab_path}}"
    dest: "{{kerberos_keytab_destination_path}}"
    owner: "{{kerberos_user}}"
    group: "{{kerberos_group}}"
    mode: 0640
  notify: "{{kerberos_handler}}"

# TODO: whether or not to do any kind of conversion for keytab file
