---
exclude_paths:
  - hosts_example.yml
skip_list:
  - risky-file-permissions
  - risky-shell-pipe
  - command-instead-of-shell
  - command-instead-of-module
  - no-changed-when
  - var-spacing
  - unnamed-task
  - meta-no-info
  - meta-no-tags
  - role-name
  - package-latest
  - empty-string-compare
  - yaml
  - no-handler
warn_list:
  # FIXME: ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.
  - syntax-check
