---
- name: Create temp folder and copy user creation script
  hosts: ad
  tasks:
    - win_file:
        state: directory
        name: C:\Temp\keytabs
    - win_copy:
        src: ./win_scripts/create_user_and_keytab.ps1
        dest: C:\Temp\keytabs\

- name: Generate Keytabs for Zookeeper
  hosts: zookeeper
  tasks:
    - import_role:
          name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{zookeeper_kerberos_user_name}}"
        kerberos_principal: "{{zookeeper_kerberos_principal}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{zookeeper_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"

- name: Generate Keytabs for Kafka Brokers
  hosts: kafka_broker
  tasks:
    - import_role:
        name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{kafka_broker_kerberos_user_name}}"
        kerberos_principal: "{{kafka_broker_kerberos_principal}}"
        extra_spn: "{{kafka_broker_extra_spn}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{kafka_broker_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"

- name: Generate Keytabs for Schema Registry
  hosts: schema_registry
  tasks:
    - import_role:
        name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{schema_registry_kerberos_user_name}}"
        kerberos_principal: "{{schema_registry_kerberos_principal}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{schema_registry_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"

- name: Generate Keytabs for Connect
  hosts: kafka_connect
  tasks:
    - import_role:
        name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{kafka_connect_kerberos_user_name}}"
        kerberos_principal: "{{kafka_connect_kerberos_principal}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{kafka_connect_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"

- name: Generate Keytabs for KSQL
  hosts: ksql
  tasks:
    - import_role:
        name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{ksql_kerberos_user_name}}"
        kerberos_principal: "{{ksql_kerberos_principal}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{ksql_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"

- name: Generate Keytabs for KSQL
  hosts: kafka_rest
  tasks:
    - import_role:
        name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{kafka_rest_kerberos_user_name}}"
        kerberos_principal: "{{kafka_rest_kerberos_principal}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{kafka_rest_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"

- name: Generate Keytabs for Control Center
  hosts: control_center
  tasks:
    - import_role:
        name: confluent.variables
    - name: Create user and keytab on the remote AD (delegated)
      include_tasks: ./tasks/generate_keytab.yml
      vars:
        kerberos_user_name: "{{control_center_kerberos_user_name}}"
        kerberos_principal: "{{control_center_kerberos_principal}}"
        script_path: C:\Temp\keytabs\create_user_and_keytab.ps1
        remote_keytab_dir: C:\Temp\keytabs
        master_keytab_file: "{{control_center_kerberos_keytab_path}}"
        ad_host: "{{groups['ad'][0]}}"


