- name: Install WikiEditTransformation on Kafka Connect Hosts
  hosts: kafka_connect
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables
    - import_role:
        name: confluent.common
      vars:
        install_java: false
    - name: Download wikiedit transform tgz, unpack into {{kafka_connect_confluent_hub_plugins_dest}}
      unarchive:
        src: "https://s3-us-west-2.amazonaws.com/muckrake-dependencies/kafka-connect-transforms-wikiedit/WikiEditTransformation-5.0.0.tar.gz"
        dest: "{{kafka_connect_confluent_hub_plugins_dest}}"
        remote_src: yes
    - name: Restart Kafka connect
      systemd:
        name: "{{ kafka_connect_service_name }}"
        state: restarted
        daemon_reload: yes
    - name: Kafka Connect Health Check
      import_role:
        name: confluent.kafka_connect
        tasks_from: health_check.yml