---
- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: false
  tags: zookeeper
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ zookeeper_service_name }}"
        config_file: "{{ zookeeper.config_file }}"
        log_dir: "{{zookeeper_log_dir}}"

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: false
  tags: kafka_broker
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ kafka_broker_service_name }}"
        config_file: "{{ kafka_broker.config_file }}"
        log_dir: "{{kafka_broker_log_dir}}"

- name: Schema Registry Provisioning
  hosts: schema_registry
  gather_facts: false
  tags: schema_registry
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ schema_registry_service_name }}"
        config_file: "{{ schema_registry.config_file }}"
        log_dir: "{{schema_registry_log_dir}}"

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: false
  tags: kafka_connect
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ kafka_connect_service_name }}"
        config_file: "{{ kafka_connect.config_file }}"
        log_dir: "{{kafka_connect_log_dir}}"

- name: KSQL Provisioning
  hosts: ksql
  gather_facts: false
  tags: ksql
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ ksql_service_name }}"
        config_file: "{{ ksql.config_file }}"
        log_dir: "{{ksql_log_dir}}"

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  gather_facts: false
  tags: kafka_rest
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ kafka_rest_service_name }}"
        config_file: "{{ kafka_rest.config_file }}"
        log_dir: "{{kafka_rest_log_dir}}"

- name: Control Center Provisioning
  hosts: control_center
  gather_facts: false
  tags: control_center
  tasks:
    - import_role:
        name: confluent.variables
    - include_tasks:
        file: roles/confluent.common/tasks/failure_handling.yml
      vars:
        service_name: "{{ control_center_service_name }}"
        config_file: "{{ control_center.config_file }}"
        log_dir: "{{control_center_log_dir}}"
