- name: Reinstall ZK and Kafka
  hosts: zookeeper:kafka_broker
  vars_prompt:
    - name: proceed
      prompt: "Reinstall ZK and Kafka? [true(default)/false]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Stop Kafka
        systemd:
          name: "{{ kafka_broker_service_name }}"
          state: stopped
      - name: Stop ZK
        systemd:
          name: "{{ zookeeper_service_name }}"
          state: stopped
      - name: Reinstall ZK and Kafka
        include_tasks: tasks/reinstall_components.yml
        vars:
          tmp_name: "zk_and_kafka"
          packages: "{{ (zookeeper_packages + kafka_broker_packages) | unique}}"
          backup_files:
            - "{{ kafka_broker.config_file }}"
            - "{{ kafka_broker.systemd_override }}"
            - "{{ kafka_broker.log_file }}"
            - "{{ zookeeper.config_file }}"
            - "{{ zookeeper.systemd_override }}"
            - "{{ zookeeper.log_file }}"
          restore_files:
            - "{{ kafka_broker.config_file }}"
            - "{{ kafka_broker.log_file }}"
            - "{{ zookeeper.config_file }}"
            - "{{ zookeeper.log_file }}"
      - name: Restart Zookeeper
        import_tasks: tasks/restart_zookeeper.yml
      - name: Restart Kafka Brokers
        import_tasks: tasks/restart_kafka.yml  
      when: proceed|bool  
    - debug:
        msg: "Skip reinstalling Zookeeper and Kafka"
      when: not proceed|bool

- name: Reinstall Schema Registry
  hosts: schema_registry
  vars_prompt:
    - name: proceed
      prompt: "Reinstall Schema Registry? [true(default)/false]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Stop Schema Registry
        systemd:
          name: "{{ schema_registry_service_name }}"
          state: stopped
      
      - name: Reinstall Schema Registry
        include_tasks: tasks/reinstall_components.yml
        vars:
          tmp_name: "schema_registry"
          packages: "{{ schema_registry_packages }}"
          backup_files:
            - "{{ schema_registry.config_file }}"
            - "{{ schema_registry.systemd_override }}"
            - "{{ schema_registry.log_file }}"
          restore_files:
            - "{{ schema_registry.config_file }}"
            - "{{ schema_registry.systemd_override }}"
            - "{{ schema_registry.log_file }}"
      
      - name: Restart Schema Registry
        import_tasks: tasks/restart_schema_registry.yml
      when: proceed|bool
    - debug:
        msg: "Skip reinstalling Schema Registry"
      when: not proceed|bool

- name: Reinstall Connect and KSQL
  hosts: kafka_connect:ksql
  vars_prompt:
    - name: proceed
      prompt: "Reinstall Connect and KSQL? [true(default)/false]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Reinstall Connect and KSQL
        include_tasks: tasks/reinstall_and_restart_components.yml
        vars:
          tmp_name: "connect_and_ksql"
          services:
            - "{{ kafka_connect_service_name }}"
            - "{{ ksql_service_name }}"
          # control center for monitoring; schema registry for AVRO stuff
          packages: "{{ (kafka_connect_packages + ksql_packages + schema_registry_packages + control_center_packages) | unique}}"
          backup_files:
            - "{{ kafka_connect.config_file }}"
            - "{{ kafka_connect.systemd_override }}"
            - "{{ kafka_connect.log_file }}"
            - "{{ ksql.config_file }}"
            - "{{ ksql.systemd_override }}"
            - "{{ ksql.log_file }}"
          restore_files:
            - "{{ kafka_connect.config_file }}"
            - "{{ kafka_connect.log_file }}"
            - "{{ ksql.config_file }}"
            - "{{ ksql.log_file }}"
      when: proceed|bool
    - debug:
        msg: "Skip reinstalling KSQL and Connect"
      when: not proceed|bool

- name: Reinstall REST Proxy and C3
  hosts: kafka_rest:control_center
  vars_prompt:
    - name: proceed
      prompt: "Reinstall REST Proxy and C3? [true(default)/false]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Reinstall REST Proxy and C3
        include_tasks: tasks/reinstall_and_restart_components.yml
        vars:
          tmp_name: "rest_and_c3"
          services:
            - "{{ kafka_rest_service_name }}"
            - "{{ control_center_service_name }}"
          # schema registry packages might be needed by rest proxy for AVRO stuff. Not sure about control center, might also need it.
          packages: "{{ (kafka_rest_packages + control_center_packages + schema_registry_packages) | unique}}"
          backup_files:
            - "{{ kafka_rest.config_file }}"
            - "{{ kafka_rest.systemd_override }}"
            - "{{ kafka_rest.log_file }}"
            - "{{ control_center.config_file }}"
            - "{{ control_center.systemd_override }}"
            - "{{ control_center.log_file }}"
          restore_files:
            - "{{ kafka_rest.config_file }}"
            - "{{ kafka_rest.log_file }}"
            - "{{ control_center.config_file }}"
            - "{{ control_center.log_file }}"
      when: proceed|bool
    - debug:
        msg: "Skip reinstalling REST Proxy and C3"
      when: not proceed|bool
      
    


    
