- name: Reinstall ZK and Kafka
  hosts: zookeeper:kafka_broker
  serial: 1
  vars_prompt:
    - name: reinstall_zk_kafka
      prompt: "Reinstall ZK and Kafka? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Stop Kafka
        systemd:
          name: "{{ kafka_broker_service_name }}"
          state: stopped
      - name: Stop ZK
        systemd:
          name: "{{ zookeeper_service_name }}"
          state: stopped
      - name: Reinstall ZK and Kafka
        include_tasks: tasks/reinstall_components.yml
        vars:
          tmp_name: "zk_and_kafka"
          packages: "{{ (zookeeper_packages + kafka_broker_packages) | unique}}"
          backup_files:
            - "{{ kafka_broker.config_file }}"
            - "{{ zookeeper.config_file }}"
          restore_files:
            - "{{ kafka_broker.config_file }}"
            - "{{ zookeeper.config_file }}"
      - name: Restart Zookeeper
        import_tasks: tasks/restart_zookeeper.yml
      - name: Restart Kafka Brokers
        import_tasks: tasks/restart_kafka.yml  
      when: reinstall_zk_kafka|bool  
    - debug:
        msg: "Skip reinstalling Zookeeper and Kafka"
      when: not reinstall_zk_kafka|bool

- name: Reinstall Schema Registry
  hosts: schema_registry
  serial: 1
  vars_prompt:
    - name: reinstall_sr
      prompt: "Reinstall Schema Registry? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Reinstall Schema Registry
        include_tasks: tasks/reinstall_and_restart_components.yml
        vars:
          tmp_name: "schema_registry"
          services:
            - "{{ schema_registry_service_name }}"
          packages: "{{ schema_registry_packages }}"
          backup_files:
            - "{{ schema_registry.config_file }}"
          restore_files:
            - "{{ schema_registry.config_file }}"
      - name: Schema Registry Health Check
        import_role:
          name: confluent.schema_registry
          tasks_from: health_check.yml
      when: reinstall_sr|bool
    - debug:
        msg: "Skip reinstalling Schema Registry"
      when: not reinstall_sr|bool

- name: Reinstall Connect and KSQL
  hosts: kafka_connect:ksql
  serial: 1
  vars_prompt:
    - name: reinstall_connect_ksql
      prompt: "Reinstall Connect and KSQL? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Reinstall Connect and KSQL
        include_tasks: tasks/reinstall_and_restart_components.yml
        vars:
          tmp_name: "connect_and_ksql"
          services:
            - "{{ kafka_connect_service_name }}"
            - "{{ ksql_service_name }}"
          # control center for monitoring; schema registry for AVRO stuff
          packages: "{{ (kafka_connect_packages + ksql_packages + schema_registry_packages + control_center_packages) | unique}}"
          # packages: "{{ (kafka_connect_packages + schema_registry_packages + control_center_packages) | unique}}"
          backup_files:
            - "{{ kafka_connect.config_file }}"
            - "{{ ksql.config_file }}"
          restore_files:
            - "{{ kafka_connect.config_file }}"
            - "{{ ksql.config_file }}"
      - name: KSQL Health Check
        import_role:
          name: confluent.ksql
          tasks_from: health_check.yml
      - name: Kafka Connect Health Check
        import_role:
          name: confluent.kafka_connect
          tasks_from: health_check.yml
      when: reinstall_connect_ksql|bool
    - debug:
        msg: "Skip reinstalling KSQL and Connect"
      when: not reinstall_connect_ksql|bool

- name: Reinstall REST Proxy and C3
  hosts: kafka_rest:control_center
  serial: 1
  vars_prompt:
    - name: reinstall_rest_c3
      prompt: "Reinstall REST Proxy and C3? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
      - name: Reinstall REST Proxy and C3
        include_tasks: tasks/reinstall_and_restart_components.yml
        vars:
          tmp_name: "rest_and_c3"
          services:
            - "{{ kafka_rest_service_name }}"
            - "{{ control_center_service_name }}"
          # schema registry packages might be needed by rest proxy for AVRO stuff. Not sure about control center, might also need it.
          packages: "{{ (kafka_rest_packages + control_center_packages + schema_registry_packages) | unique}}"
          backup_files:
            - "{{ kafka_rest.config_file }}"
            - "{{ control_center.config_file }}"
          restore_files:
            - "{{ kafka_rest.config_file }}"
            - "{{ control_center.config_file }}"
      - name: Kafka Rest Health Check
        import_role:
          name: confluent.kafka_rest
          tasks_from: health_check.yml
      - name: Control Center Health Check
        import_role:
          name: confluent.control_center
          tasks_from: health_check.yml
      when: reinstall_rest_c3|bool
    - debug:
        msg: "Skip reinstalling REST Proxy and C3"
      when: not reinstall_rest_c3|bool
      
    


    
