- name: Stop everything
  hosts: all
  tasks:
    - shell: "systemctl stop 'confluent-*'"

- name: Restart Zookeeper
  hosts: zookeeper
  tasks:
    - import_role:
        name: confluent.variables_handlers
    - name: Restart Zookeeper
      import_tasks: tasks/restart_zookeeper.yml

- name: Restart Kafka
  hosts: kafka_broker
  tasks:
    - import_role:
        name: confluent.variables_handlers
    - name: Restart Kafka
      import_tasks: tasks/restart_kafka.yml

- name: Restart Schema Registry
  hosts: schema_registry
  tasks:
    - import_tasks: tasks/restart_schema_registry.yml

- name: Restart Connect
  hosts: kafka_connect
  tasks:
    - systemd:
        name: "{{ kafka_connect_service_name }}"
        state: restarted
        daemon_reload: yes

- name: Restart KSQL
  hosts: ksql
  tasks:
    - systemd:
        name: "{{ ksql_service_name }}"
        state: restarted
        daemon_reload: yes

- name: Retart REST Proxy
  hosts: kafka_rest
  tasks:
    - systemd:
        name: "{{ kafka_rest_service_name }}"
        state: restarted
        daemon_reload: yes

- name: Restart C3
  hosts: control_center
  tasks:
    - systemd:
        name: "{{ kafka_rest_service_name }}"
        state: restarted
        daemon_reload: yes
