# Rolling restart of Zookeeper nodes
- name: Roll Zookeeper
  hosts: zookeeper
  serial: 1
  vars_prompt:
    - name: roll_zk
      prompt: "Roll Zookeeper? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart Zookeeper
        import_tasks: tasks/restart_zookeeper.yml
      when: roll_zk|bool
    - debug:
        msg: "Skip rolling Zookeeper"
      when: not roll_zk|bool

# Rolling restart of Kafka broker nodes
- name: Roll Kafka
  hosts: kafka_broker
  serial: 1
  vars_prompt:
    - name: roll_kafka
      prompt: "Roll Kafka? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart Kafka Brokers
        import_tasks: tasks/restart_kafka.yml  
      when: roll_kafka|bool
    - debug:
        msg: "Skip rolling Kafka"
      when: not roll_kafka|bool

# Rolling restart of Schema Registry nodes
- name: Roll Schema Registry
  hosts: schema_registry
  serial: 1
  vars_prompt:
    - name: roll_sr
      prompt: "Roll Schema Registry? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart Schema Registry
        systemd:
          name: "{{ schema_registry_service_name }}"
          state: restarted
      - name: Schema Registry Health Check
        import_role:
          name: confluent.schema_registry
          tasks_from: health_check.yml
        when: health_checks_enabled|bool
      when: roll_sr|bool
    - debug:
        msg: "Skip rolling Schema Registry"
      when: not roll_sr|bool

# Rolling restart of Kafka Connect nodes
- name: Roll Connect
  hosts: kafka_connect
  serial: 1
  vars_prompt:
    - name: roll_connect
      prompt: "Roll Kafka Connect? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart Kafka Connect
        systemd:
          name: "{{ kafka_connect_service_name }}"
          state: restarted
      - name: Kafka Connect Health Check
        import_role:
          name: confluent.kafka_connect
          tasks_from: health_check.yml
        when: health_checks_enabled|bool
      when: roll_connect|bool
    - debug:
        msg: "Skip rolling Kafka Connect"
      when: not roll_connect|bool

# Rolling restart of KSQL nodes
- name: Roll KSQL
  hosts: ksql
  serial: 1
  vars_prompt:
    - name: roll_ksql
      prompt: "Roll KSQL? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart KSQL
        systemd:
          name: "{{ ksql_service_name }}"
          state: restarted
      - name: KSQL Health Check
        import_role:
          name: confluent.ksql
          tasks_from: health_check.yml
        when: health_checks_enabled|bool
      when: roll_ksql|bool
    - debug:
        msg: "Skip rolling KSQL"
      when: not roll_ksql|bool

# Rolling restart of REST Proxy (standalone) nodes
- name: Roll Kafka REST Proxy
  hosts: kafka_rest
  serial: 1
  vars_prompt:
    - name: roll_kafka_rest
      prompt: "Roll Kafka REST Proxy? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart Kafka Rest
        systemd:
          name: "{{ kafka_rest_service_name }}"
          state: restarted
      - name: Kafka Rest Health Check
        import_role:
          name: confluent.kafka_rest
          tasks_from: health_check.yml
        when: health_checks_enabled|bool
      when: roll_kafka_rest|bool
    - debug:
        msg: "Skip rolling Kafka REST Proxy"
      when: not roll_kafka_rest|bool

# Rolling restart of Control Center nodes
- name: Roll Control Center
  hosts: control_center
  serial: 1
  vars_prompt:
    - name: roll_c3
      prompt: "Roll Control Center? [yes(default)/no]"
      private: no
      default: true
  tasks:
    - block:
      - import_role:
          name: confluent.variables
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Restart Control Center
        systemd:
          name: "{{ control_center_service_name }}"
          state: restarted
      - name: Control Center Health Check
        import_role:
          name: confluent.control_center
          tasks_from: health_check.yml
        when: health_checks_enabled|bool
      when: roll_c3|bool
    - debug:
        msg: "Skip rolling Control Center"
      when: not roll_c3|bool
      
    


    
