- name: Testing
  hosts: control_center
  serial: 1
  tasks:
    - block:
      - import_role:
          name: confluent.variables_handlers
      - import_role:
          name: confluent.common
        vars:
          install_java: false
      - name: Backup and restore
        include_tasks: tasks/backup_restore_test.yml
        vars:
          tmp_name: test_backup_restore
          backup_files:
            - "{{ kafka_rest.config_file }}"
            - "{{ kafka_rest.systemd_override }}"
            - "{{ kafka_rest.log4j_file }}"
            - "{{ control_center.config_file }}"
            - "{{ control_center.systemd_override }}"
            - "{{ control_center.log4j_file }}"