- name: Testing
  hosts: control_center
  tasks:
    - name: Remove the Packages - Red Hat
      yum:
        name: "confluent-*"
        state: absent
        autoremove: yes
      when: ansible_os_family == "RedHat"