---
- name: Create SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
  when: copy_certs | default(True)

- name: Copy in MDS Public Pem File
  copy:
    src: "{{ kafka_connect_replicator_producer_erp_pem_file }}"
    dest: "{{ kafka_connect_replicator_producer_rbac_enabled_public_pem_path }}"
    mode: 0640
    owner: "{{user}}"
    group: "{{group}}"
  when: copy_certs | default(True)

# Take confluent_replicator_white_list property, split into list
- name: Set Replicator Topic White List
  set_fact:
    topic_white_list: "{{ kafka_connect_replicator_white_list.split(',') | default('')| difference(['']) }} "

- name: Grant Confluent Replicator User ResourceOwner on White List Topics
  uri:
    url: "{{confluent_replicator_mds_url.split(',')[0]| default('localhost:8090')}}/security/1.0/principals/{{kafka_connect_replicator_producer_ldap_principal}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{confluent_replicator_erp_admin_user}}"
    url_password: "{{confluent_replicator_erp_admin_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_connect_replicator_producer_kafka_cluster_id}}"}},
            "resourcePatterns": [
              {
                "resourceType":"Topic",
                "name":"{{ item }}",
                "patternType":"LITERAL"
              }
            ]
          }
        }
      }
    status_code: 204
  with_items: "{{ topic_white_list }}"
