---
- name: Create SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
  when: copy_certs | default(True)

- name: Copy in MDS Public Pem File
  copy:
    src: "{{ kafka_connect_replicator_consumer_erp_pem_file }}"
    dest: "{{ kafka_connect_replicator_consumer_rbac_enabled_public_pem_path }}"
    mode: 0640
    owner: "{{user}}"
    group: "{{group}}"
  when: copy_certs | default(True)

- name: Grant Confluent Replicator User Developer Read on White List Topics on Source Cluster
  uri:
    url: "{{confluent_replicator_consumer_mds_url.split(',')[0]| default('localhost:8090')}}/security/1.0/principals/{{kafka_connect_replicator_consumer_ldap_principal}}/roles/DeveloperRead/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{confluent_replicator_consumer_erp_admin_user}}"
    url_password: "{{confluent_replicator_consumer_erp_admin_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_connect_replicator_consumer_kafka_cluster_id}}"}},
            "resourcePatterns": [
              {
                "resourceType":"Topic",
                "name":"{{ item }}",
                "patternType":"LITERAL"
              }
            ]
          }
        }
      }
    status_code: 204
  with_items: "{{ topic_white_list }}"

- name: Grant Confluent Replicator User Developer Manage on White List Topics on Source Cluster
  uri:
    url: "{{confluent_replicator_consumer_mds_url.split(',')[0]| default('localhost:8090')}}/security/1.0/principals/{{kafka_connect_replicator_consumer_ldap_principal}}/roles/DeveloperManage/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{confluent_replicator_consumer_erp_admin_user}}"
    url_password: "{{confluent_replicator_consumer_erp_admin_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_connect_replicator_consumer_kafka_cluster_id}}"}},
            "resourcePatterns": [
              {
                "resourceType":"Topic",
                "name":"{{ item }}",
                "patternType":"LITERAL"
              }
            ]
          }
        }
      }
    status_code: 204
  with_items: "{{ topic_white_list }}"
