---
# Run these tasks over kafka_broker group
# Creates two variable defined groups: non_controller_group, controller
# confluent_server_enabled must be set correctly for the host
- import_role:
    name: confluent.kafka_broker
    tasks_from: dynamic_groups.yml
  vars:
    kafka_broker_controller_group: "{{ controller_group }}"
    kafka_broker_non_controller_group: "{{ non_controller_group }}"
