---
- block:
  - name: Create user and keytab on the remote AD (delegated)
    win_shell: >-
              {{script_path}} 
              -ad_domain {{qe_ad_domain}} 
              -ldap_root "{{qe_ldap_root}}"
              -user_name {{kerberos_user_name}}
              -upn {{kerberos_principal}}
              -extra_spn {{external_hostname | default('')}}
              -keytab_dir {{remote_keytab_dir}}
  - name: Fetch newly generated keytab to ansible master (delegated)
    fetch:
      src: "{{remote_keytab_dir}}/{{kerberos_user_name}}.keytab"
      dest: "{{master_keytab_file}}"
      flat: True
  delegate_to: "{{ad_host}}"
  delegate_facts: True


