- name: Start ZK
  systemd:
    name: "{{ zookeeper_service_name }}"
    state: restarted
    daemon_reload: yes

- name: Zookeeper Health Check
  import_role:
    name: confluent.zookeeper
    tasks_from: health_check.yml
  when: health_checks_enabled|bool