---
- name: Add new brokers Nodes into in-memory inventory to scale-up
  hosts: all
  gather_facts: false
  tasks:
    - name: "Add new Broker Node kafka-broker4"
      add_host:
        hostname: kafka-broker4
        groups: kafka_broker

    - name: "Add new Broker Node kafka-broker5"
      add_host:
        hostname: kafka-broker5
        groups: kafka_broker

- name: Converge
  import_playbook: confluent.platform.all
