---
- name: Add new brokers Nodes into in-memory inventory to scale-up
  hosts: all
  gather_facts: false
  tasks:
    - name: "Add new Broker Nodes"
      add_host:
        hostname: kafka-broker4
        ansible_connection: community.docker.docker
        groups: kafka_broker
        tag: kafka_broker

    - name: "Add new Broker Nodes"
      add_host:
        hostname: kafka-broker5
        ansible_connection: community.docker.docker
        groups: kafka_broker
        tag: kafka_broker

    - name: "Print Test"
      debug:
        msg: 
          - "{{ groups['kafka_broker'] }}"
          - "Printing broker1 group names"
          - "{{ hostvars['kafka-broker1'].group_names }}"
          - "Printing broker5 group names"
          - "{{ hostvars['kafka-broker5'].group_names }}"

- name: Converge
  import_playbook: confluent.platform.all
