---
# More control_center variables are defined in the confluent.variables role

control_center_java_args:
  - "{% if control_center_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"

### Custom Java Args to add to the Control Center Process
control_center_custom_java_args: ""

control_center_final_java_args: "{{ control_center_java_args + [ control_center_custom_java_args ] }}"

### Full Path to the RocksDB Data Directory. If left as empty string, cp-ansible will not configure RocksDB
control_center_rocksdb_path: ""

# Empty values will not be written into override.conf
control_center_service_overrides:
  User: "{{ control_center_user if control_center_user != control_center_default_user else '' }}"
  Group: "{{ control_center_group if control_center_group != control_center_default_group else '' }}"
  ExecStart: "{% if installation_method == 'archive' %}{{ control_center.server_start_file }} {{ control_center.config_file }}{% endif %}"

# Empty values will not be written into override.conf
control_center_service_environment_overrides:
  ROCKSDB_SHAREDLIB_DIR: "{{control_center_rocksdb_path}}"
  CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
  CONTROL_CENTER_OPTS: "{{ control_center_final_java_args | java_arg_build_out }}"
  # Remove trailing slash if there is one
  LOG_DIR: "{{ control_center_log_dir|regex_replace('\\/$', '') if control_center_log_dir|regex_replace('\\/$', '') != control_center_default_log_dir else '' }}"
  CONFLUENT_SECURITY_MASTER_KEY: "{% if control_center_secrets_protection_enabled|bool %}{{secrets_protection_masterkey}}{% endif %}"
