---
- name: Restart Kafka Connect
  systemd:
    daemon_reload: true
    name: "{{kafka_connect_service_name}}"
    state: restarted
  tags:
    - systemd
  when: not ansible_check_mode

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_connect_health_check_delay }}"
