---
- name: Restart KSQL
  systemd:
    daemon_reload: true
    name: "{{ksql_service_name}}"
    state: restarted
  tags:
    - systemd
  when: not ansible_check_mode

- name: Startup Delay
  wait_for:
    timeout: "{{ ksql_health_check_delay }}"
