---
- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - name: Check jaas config properly set
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: client.sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";'

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    # TODO do i need to check this in other components
    - name: Check Replication Factor set to 3 eventhough there is no kafka group in inventory
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.internal.topic.replicas
        expected_value: "3"
