---
driver:
  name: docker
platforms:
  - name: ldap1
    hostname: ldap1.confluent
    groups:
      - ldap_server
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: zookeeper1
    hostname: zookeeper1.confluent
    groups:
      - zookeeper
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker2
    hostname: kafka-broker2.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker3
    hostname: kafka-broker3.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: schema-registry1
    hostname: schema-registry1.confluent
    groups:
      - schema_registry
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-rest1
    hostname: kafka-rest1.confluent
    groups:
      - kafka_rest
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-connect1
    hostname: kafka-connect1.confluent
    groups:
      - kafka_connect
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: ksql1
    hostname: ksql1.confluent
    groups:
      - ksql
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: control-center1
    hostname: control-center1.confluent
    groups:
      - control_center
    image: geerlingguy/docker-ubuntu1804-ansible
    dockerfile: ../Dockerfile-ubuntu.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ../../../../all.yml
  inventory:
    group_vars:
      all:
        scenario_name: mtls-provided-fips-ubuntu

        ssl_enabled: true
        ssl_mutual_auth_enabled: true

        fips_enabled: true

        kafka_broker_custom_java_args: "-Djavax.net.debug=ssl"

        ssl_provided_keystore_and_truststore: true
        ssl_keystore_filepath: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/{{inventory_hostname}}.keystore.jks"
        ssl_keystore_key_password: keystorepass
        ssl_keystore_store_password: keystorepass
        ssl_truststore_filepath: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/truststore.jks"
        ssl_truststore_password: truststorepass
        ssl_truststore_ca_cert_alias: CARoot

      # Need the keystore alias for bcfks conversion
      zookeeper:
        ssl_keystore_alias: "zookeeper.{{inventory_hostname}}"
      kafka_broker:
        ssl_keystore_alias: "kafka_broker.{{inventory_hostname}}"
      kafka_connect:
        ssl_keystore_alias: "kafka_connect.{{inventory_hostname}}"
      kafka_rest:
        ssl_keystore_alias: "kafka_rest.{{inventory_hostname}}"
      schema_registry:
        ssl_keystore_alias: "schema_registry.{{inventory_hostname}}"
      ksql:
        ssl_keystore_alias: "ksql.{{inventory_hostname}}"
      control_center:
        ssl_keystore_alias: "control_center.{{inventory_hostname}}"

verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint ../..
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
