---
- name: Copy CA Cert to Host
  copy:
    remote_src: "{{ssl_custom_certs_remote_src}}"
    src: "{{ssl_ca_cert_filepath}}"
    dest: "{{ca_cert_path}}"

# - name: Copy Signed Cert to Host
#   copy:
#     remote_src: "{{ssl_custom_certs_remote_src}}"
#     src: "{{ssl_signed_cert_filepath}}"
#     dest: "{{cert_path}}"

- name: Copy Signed Cert to Host
  copy:
    remote_src: "{{ssl_custom_certs_remote_src}}"
    src: "{{ssl_signed_cert_filepath}}"
    dest: "/var/ssl/private/{{service_name}}.chain"

- name: Extract Final Cert from Signed Cert Chain
  shell: |
    tac /var/ssl/private/{{service_name}}.chain | awk '!flag; /-----BEGIN CERTIFICATE-----/{flag = 1};' | tac > {{cert_path}}

- name: Copy Key to Host
  copy:
    remote_src: "{{ssl_custom_certs_remote_src}}"
    src: "{{ssl_key_filepath}}"
    dest: "{{key_path}}"

- name: Create Keystore and Truststore from Certs
  include_tasks: create_keystores_from_certs.yml
