---
- name: Copy CA Cert to Host
  copy:
    src: "generated_ssl_files/{{ssl_self_signed_ca_cert_filename}}"
    dest: "{{ca_cert_path}}"

- name: Copy CA Key to Host
  copy:
    src: "generated_ssl_files/{{ssl_self_signed_ca_key_filename}}"
    dest: "{{ca_key_path}}"

- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{truststore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{ca_cert_path}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}}

- name: Create Host Key
  shell: |
    openssl genrsa -out {{key_path}} \
      2048 -passout pass:{{keystore_storepass}}

- name: Create Certificate Signing Request
  shell: |
    openssl req -new -key {{key_path}} \
      -out /var/ssl/private/generation/client.csr \
      -subj '/CN=kafka_broker/OU=TEST/O=CONFLUENT/L=PaloAlto/ST=Ca/C=US'

- name: Create Openssl Config for SAN
  template:
    src: openssl-san.cnf.j2
    dest: /var/ssl/private/generation/openssl-san.cnf

- name: Sign CSR with the Certificate Authority
  shell: |
    openssl x509 -req -CA {{ca_cert_path}} \
      -CAkey {{ca_key_path}} \
      -in /var/ssl/private/generation/client.csr \
      -out {{cert_path}} \
      -days {{keystore_expiration_days}} -CAcreateserial \
      -passin pass:{{ssl_self_signed_ca_password}} \
      -extfile /var/ssl/private/generation/openssl-san.cnf \
      -extensions v3_req

- name: Create Cert Chain
  shell: |
    cat {{ca_cert_path}} {{cert_path}} > /var/ssl/private/generation/signed-cert-chain.crt

- name: Create Keystore with Key and Signed Cert Chain
  shell: |
    openssl pkcs12 -export \
      -in /var/ssl/private/generation/signed-cert-chain.crt \
      -inkey {{key_path}} \
      -chain -out {{keystore_path}} \
      -name localhost \
      -CAfile /var/ssl/private/ca.crt -caname CARoot \
      -password pass:{{keystore_storepass}}

- name: Import the CA cert into the Keystore
  shell: |
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{ca_cert_path}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}
