---
- name: Copy CA Cert to Host
  copy:
    src: "generated_ssl_files/{{ssl_self_signed_ca_cert_filename}}"
    dest: "{{ca_cert_path}}"

- name: Copy CA Key to Host
  copy:
    src: "generated_ssl_files/{{ssl_self_signed_ca_key_filename}}"
    dest: "{{ca_key_path}}"

- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore /var/ssl/private/{{service_name}}.truststore.p12 \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{ca_cert_path}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}}

- name: Convert Truststore to BCFKS - FIPS
  shell: |
    keytool -importkeystore -v \
      -srckeystore /var/ssl/private/{{service_name}}.truststore.p12 \
      -srcstorepass {{truststore_storepass}} \
      -srcalias CARoot \
      -srcstoretype PKCS12 \
      -destkeystore /var/ssl/private/{{service_name}}.truststore.bcfks \
      -deststorepass {{truststore_storepass}} \
      -destalias CARoot \
      -deststoretype BCFKS \
      -providername BCFIPS \
      -providerclass org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
      -providerpath /usr/share/java/kafka/bc-fips-*.jar
  when: convert_to_bcfks|default(False)|bool

- name: Create Keystore
  shell: |
    keytool -genkeypair -noprompt \
      -storetype pkcs12 \
      -keyalg {{ssl_key_algorithm}} -keysize {{ssl_key_size}} \
      -alias {{inventory_hostname}} \
      -dname "CN={{service_name}},OU=TEST,O=CONFLUENT,L=PaloAlto,S=Ca,C=US" \
      -ext "SAN={{hostnames | cert_extension}}" \
      -keystore /var/ssl/private/{{service_name}}.keystore.p12 \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

- name: Export Key from Keystore
  shell: |
    openssl pkcs12 \
        -in /var/ssl/private/{{service_name}}.keystore.p12 \
        -passin pass:{{keystore_storepass}} \
        -nodes -nocerts \
        -out {{key_path}}

- name: Create Certificate Signing Request
  shell: |
    keytool -keystore /var/ssl/private/{{service_name}}.keystore.p12 \
      -storetype pkcs12 \
      -alias {{inventory_hostname}} \
      -certreq -file /var/ssl/private/generation/client.csr \
      -ext "SAN={{hostnames | cert_extension}}" \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

- name: Create Openssl Config for SAN
  template:
    src: openssl-san.cnf.j2
    dest: /var/ssl/private/generation/openssl-san.cnf

- name: Sign CSR with the Certificate Authority
  shell: |
    openssl x509 -req -CA {{ca_cert_path}} \
      -CAkey {{ca_key_path}} \
      -in /var/ssl/private/generation/client.csr \
      -out {{cert_path}} \
      -days {{keystore_expiration_days}} -CAcreateserial \
      -passin pass:{{ssl_self_signed_ca_password}} \
      -extfile /var/ssl/private/generation/openssl-san.cnf \
      -extensions v3_req

- name: Import the CA cert into the Keystore
  shell: |
    keytool -noprompt -keystore /var/ssl/private/{{service_name}}.keystore.p12 \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{ca_cert_path}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

- name: Create Cert Chain
  shell: |
    cat {{ca_cert_path}} {{cert_path}} > /var/ssl/private/generation/signed-cert-chain.crt

- name: Import the Signed Host Cert into the Keystore
  shell: |
    keytool -noprompt -keystore /var/ssl/private/{{service_name}}.keystore.p12 \
      -storetype pkcs12 \
      -alias {{inventory_hostname}} \
      -import -file /var/ssl/private/generation/signed-cert-chain.crt \
      -ext "SAN={{hostnames | cert_extension}}" \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

- name: Convert Keystore to BCFKS - FIPS
  shell: |
    keytool -importkeystore -v \
      -srckeystore /var/ssl/private/{{service_name}}.keystore.p12 \
      -srcstorepass {{keystore_storepass}} \
      -srcalias {{inventory_hostname}} \
      -srcstoretype PKCS12 \
      -destkeystore /var/ssl/private/{{service_name}}.keystore.bcfks \
      -deststorepass {{keystore_storepass}} \
      -destalias {{inventory_hostname}}  \
      -deststoretype BCFKS \
      -providername BCFIPS \
      -providerclass org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
      -providerpath /usr/share/java/kafka/bc-fips-*.jar
  when: convert_to_bcfks|default(False)|bool
