---
- name: Remove the ${CONTROLLER_HOSTGROUP:-zookeeper} and Kafka Broker Groups from Inventory
  hosts: ${CONTROLLER_HOSTGROUP:-zookeeper}:kafka_broker
  gather_facts: false
  tasks:
    - name: Change ${CONTROLLER_HOSTGROUP:-zookeeper} Group Name in Inventory File
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: '${CONTROLLER_HOSTGROUP:-zookeeper}:'
        line: '${CONTROLLER_HOSTGROUP:-zookeeper}_ccloud:'
      delegate_to: 127.0.0.1
      run_once: true

    - name: Change kafka_broker Group Name in Inventory File
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: 'kafka_broker:'
        line: 'kafka_broker_ccloud:'
      delegate_to: 127.0.0.1
      run_once: true

    - name: Refresh Inventory
      meta: refresh_inventory

- name: Converge
  import_playbook: confluent.platform.all
