---
driver:
  name: docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
  config_options:
    defaults:
      hash_behaviour: merge
verifier:
  name: ansible
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
