---
- name: Confirm Hash Merging Enabled
  assert:
    that: lookup('config', 'DEFAULT_HASH_BEHAVIOUR') == 'merge'
    fail_msg: "Hash Merging must be enabled in ansible.cfg: Confirm current directory is cp-ansible and permissions are set to 755 not 777"

- name: Confirm Rhel Version Supported
  assert:
    that: ansible_distribution_major_version in ['7', '8']
    fail_msg: "Rhel Version: {{ansible_distribution_major_version}} not in supported versions: 7, 8"
  when: ansible_os_family == "RedHat"

- name: Confirm Ubuntu Version Supported
  assert:
    that: ansible_distribution_major_version in ['16', '18']
    fail_msg: "Ubuntu Version: {{ansible_distribution_major_version}} not in supported versions: 16, 18"
  when: ansible_distribution == "Ubuntu"

- name: Confirm Debian Version Supported
  assert:
    that: ansible_distribution_major_version in ['9']
    fail_msg: "Debian Version: {{ansible_distribution_major_version}} not in supported versions: 9"
  when: ansible_distribution == "Debian"
