---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.variables

    - name: Get stats on copied file
      stat:
        path: "/opt/confluent/confluent-{{confluent_package_version}}"
      register: archive

    - name: Assert copied file's permissions correct
      assert:
        that:
          - archive.stat.exists
          - archive.stat.gr_name == 'custom'
          - archive.stat.pw_name == 'cp-custom'
        quiet: true
