---
name: Lint Code Base
on:
  - pull_request
  - push
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Uncomment to only run on files changed in PR
          # VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: .
          VALIDATE_YAML: true
